ALTER TABLE pessoa
  ADD COLUMN IF NOT EXISTS genero VARCHAR(30),
  ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(120),
  ADD COLUMN IF NOT EXISTS naturalidade VARCHAR(120),
  ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(30),
  ADD COLUMN IF NOT EXISTS data_nascimento DATE;
